# Project: MyVirust
# Makefile created by Dev-C++ 5.3.0.4

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = MyVirust.o main.o $(RES)
LINKOBJ  = MyVirust.o main.o $(RES)
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include"
BIN      = MyVirust.exe
CXXFLAGS = $(CXXINCS)  -g3
CFLAGS   = $(INCS)  -g3
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

MyVirust.o: MyVirust.cpp
	$(CPP) -c MyVirust.cpp -o MyVirust.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
